# Generated by Django 5.1.6 on 2025-02-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image_style',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
